version = 0.1

[default.deploy.parameters]
stack_name = "fpl-market-snapshot"
resolve_s3 = true
s3_prefix = "fpl-market-snapshot"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AlertEmail=\"skyefung02@gmail.com\" ScheduleExpression=\"rate(5 minutes)\" MinRunsPerHour=\"6\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
